In [1]:
import pandas as pd
import numpy as np

In [2]:
def clean(x):
    day = x.split('/')[0]
    month = x.split('/')[1]
    year = x.split('/')[2]
    return '20' + year + '-' + month + '-' + day

In [3]:
campaign_data = pd.read_csv('../data/data/campaign_data.csv', parse_dates=False)

In [4]:
campaign_data.head()

   campaign_id campaign_type start_date  end_date
0           24             Y   21/10/13  20/12/13
1           25             Y   21/10/13  22/11/13
2           20             Y   07/09/13  16/11/13
3           23             Y   08/10/13  15/11/13
4           21             Y   16/09/13  18/10/13

In [5]:
campaign_data['start_date'] = campaign_data['start_date'].map(clean)
campaign_data['end_date'] = campaign_data['end_date'].map(clean)

In [6]:
campaign_data.head()

   campaign_id campaign_type  start_date    end_date
0           24             Y  2013-10-21  2013-12-20
1           25             Y  2013-10-21  2013-11-22
2           20             Y  2013-09-07  2013-11-16
3           23             Y  2013-10-08  2013-11-15
4           21             Y  2013-09-16  2013-10-18

In [ ]:
campaign_data.to_csv('../data/data/campaign_data_clean.csv', index=False)