In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../data/data/customer_transaction_data.csv')
mapping = pd.read_csv('../data/data/coupon_item_mapping.csv')
data = data.merge(mapping, on='item_id')

In [3]:
data.head()

,date,customer_id,item_id,quantity,selling_price,other_discount,coupon_discount,coupon_id
0,2012-01-02,1501,26830,1,35.26,-10.69,0.0,7
1,2012-01-02,1501,26830,1,35.26,-10.69,0.0,20
2,2012-01-02,1501,26830,1,35.26,-10.69,0.0,29
3,2012-01-02,135,26830,1,35.26,-10.69,0.0,7
4,2012-01-02,135,26830,1,35.26,-10.69,0.0,20

In [4]:
feat_1 = data.groupby('coupon_id')['selling_price'].sum().reset_index()
feat_2 = data.groupby('coupon_id')['quantity'].sum().reset_index()
feat_3 = data.groupby('coupon_id')['other_discount'].sum().reset_index()
feat_4 = data.groupby('coupon_id')['coupon_discount'].sum().reset_index()
feat_5 = data.groupby('coupon_id')['coupon_discount'].agg(np.count_nonzero).reset_index()

In [5]:
feat_1.columns = ['coupon_id','sum_coup_prc'] 
feat_2.columns = ['coupon_id','sum_coup_qty'] 
feat_3.columns = ['coupon_id','sum_coup_dsc']
feat_4.columns = ['coupon_id','sum_coup_cdsc']
feat_5.columns = ['coupon_id','cnt_coup_cdsc']

In [6]:
driver = pd.read_csv('../data/driver.csv')

In [7]:
driver = driver.merge(feat_1, on='coupon_id')
driver = driver.merge(feat_2, on='coupon_id')
driver = driver.merge(feat_3, on='coupon_id')
driver = driver.merge(feat_4, on='coupon_id')
driver = driver.merge(feat_5, on='coupon_id')

In [8]:
driver = driver.drop(['campaign_id','coupon_id','customer_id'], axis=1)

In [9]:
driver.shape

(128595, 6)

In [10]:
driver.head()

,id,sum_coup_prc,sum_coup_qty,sum_coup_dsc,sum_coup_cdsc,cnt_coup_cdsc
0,1,318372.92,4661,-225584.38,-5349.93,191.0
1,370,318372.92,4661,-225584.38,-5349.93,191.0
2,554,318372.92,4661,-225584.38,-5349.93,191.0
3,1958,318372.92,4661,-225584.38,-5349.93,191.0
4,2075,318372.92,4661,-225584.38,-5349.93,191.0

In [11]:
driver.to_csv('../data/feature/coupon_spend_profile.csv', index=False)