In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
def encodeLabel(data, feature):
    encoder = LabelEncoder()
    data[feature] = encoder.fit_transform(data[feature].fillna('none'))
    return data

In [3]:
driver = pd.read_csv('../data/driver.csv')

In [4]:
data = pd.read_csv('../data/data/customer_transaction_data.csv')
item = pd.read_csv('../data/data/item_data.csv')
mapping = pd.read_csv('../data/data/coupon_item_mapping.csv')
data = data[data['coupon_discount'] == 0]

In [5]:
item = encodeLabel(item, 'brand')
item = encodeLabel(item, 'brand_type')
item = encodeLabel(item, 'category')

In [6]:
data = data.groupby(['customer_id','item_id'])[['selling_price','quantity','other_discount']].sum().reset_index()

In [7]:
data = data.merge(item, on=['item_id'])
data = data.merge(mapping, on=['item_id'])

In [8]:
data.head()

,customer_id,item_id,selling_price,quantity,other_discount,brand,brand_type,category,coupon_id
0,1,4796,106.5,1,0.0,277,0,6,21
1,1,4796,106.5,1,0.0,277,0,6,30
2,4,4796,213.0,2,0.0,277,0,6,21
3,4,4796,213.0,2,0.0,277,0,6,30
4,7,4796,106.5,1,0.0,277,0,6,21

In [9]:
feat_1 = data.groupby(['customer_id','coupon_id'])['item_id'].count().reset_index()
feat_1 = feat_1.rename(columns={'item_id':'cnt_trx_cust_coup_item'})

In [10]:
feat_2 = data.groupby(['customer_id','coupon_id'])['quantity'].sum().reset_index()
feat_2 = feat_2.rename(columns={'quantity':'sum_trx_cust_coup_qty'})
feat_3 = data.groupby(['customer_id','coupon_id'])['selling_price'].sum().reset_index()
feat_3 = feat_3.rename(columns={'selling_price':'sum_trx_cust_coup_price'})
feat_4 = data.groupby(['customer_id','coupon_id'])['other_discount'].sum().reset_index()
feat_4 = feat_4.rename(columns={'other_discount':'sum_trx_cust_coup_dsc'})

In [11]:
feat_5 = data.groupby(['customer_id','coupon_id'])['quantity'].mean().reset_index()
feat_5 = feat_5.rename(columns={'quantity':'avg_trx_cust_coup_qty'})
feat_6 = data.groupby(['customer_id','coupon_id'])['selling_price'].mean().reset_index()
feat_6 = feat_6.rename(columns={'selling_price':'avg_trx_cust_coup_price'})
feat_7 = data.groupby(['customer_id','coupon_id'])['other_discount'].mean().reset_index()
feat_7 = feat_7.rename(columns={'other_discount':'avg_trx_cust_coup_dsc'})

In [12]:
feat_8 = data.groupby(['customer_id','coupon_id'])['quantity'].max().reset_index()
feat_8 = feat_8.rename(columns={'quantity':'max_trx_cust_coup_qty'})
feat_9 = data.groupby(['customer_id','coupon_id'])['selling_price'].max().reset_index()
feat_9 = feat_9.rename(columns={'selling_price':'max_trx_cust_coup_price'})
feat_10 = data.groupby(['customer_id','coupon_id'])['other_discount'].max().reset_index()
feat_10 = feat_10.rename(columns={'other_discount':'max_trx_cust_coup_dsc'})

In [13]:
driver = driver.merge(feat_1, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_2, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_3, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_4, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_5, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_6, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_7, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_8, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_9, on=['customer_id','coupon_id'], how='left')
driver = driver.merge(feat_10, on=['customer_id','coupon_id'], how='left')
driver = driver.fillna(0)

In [14]:
driver = driver.drop(['campaign_id','coupon_id','customer_id'], axis=1)

In [15]:
driver.to_csv('../data/feature/tranx_item_feature.csv', index=False)

In [16]:
driver.shape

(128595, 11)

In [17]:
driver.head()

,id,cnt_trx_cust_coup_item,sum_trx_cust_coup_qty,sum_trx_cust_coup_price,sum_trx_cust_coup_dsc,avg_trx_cust_coup_qty,avg_trx_cust_coup_price,avg_trx_cust_coup_dsc,max_trx_cust_coup_qty,max_trx_cust_coup_price,max_trx_cust_coup_dsc
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0