In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import QuantileTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
np.random.seed(2017)

In [3]:
FEATURES = ['score' + str(x+1) for x in range(7)]
TARGET = ['target']

In [4]:
train = pd.read_csv('../../data/combined/data.csv')
train = train[train['source'] == 'ISIC20']
train = train[['image_id','fold','target']]
score1 = pd.read_csv('../../score/public_train_920.csv')[['image_name','pred']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/public_train_925.csv')[['image_name','predictions']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/public_train_945.csv')[['image_name','pred']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/public_train_946.csv')[['image_name','pred']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/public_train_947.csv')[['image_name','target']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/public_train_949.csv')[['image_name','predictions']]
score6.columns = ['image_id','score6']
score7 = pd.read_csv('../../score/public_train_936.csv')[['image_name','pred']]
score7.columns = ['image_id','score7']
train = train.merge(score1, on='image_id')
train = train.merge(score2, on='image_id')
train = train.merge(score3, on='image_id')
train = train.merge(score4, on='image_id')
train = train.merge(score5, on='image_id')
train = train.merge(score6, on='image_id')
train = train.merge(score7, on='image_id')

In [5]:
for idx in range(8):
    idx += 1
    try:
        print('Model:',idx,'AUC:',roc_auc_score(train.target, train['score'+str(idx)]))
    except:
        pass

Model: 1 AUC: 0.9251110774012096
Model: 2 AUC: 0.9188854363040988
Model: 3 AUC: 0.9037831443226302
Model: 4 AUC: 0.9197216860501578
Model: 5 AUC: 0.9095914377803066
Model: 6 AUC: 0.9163052351774854
Model: 7 AUC: 0.9032827130919907

In [6]:
test = pd.read_csv('../../data/combined/sample_submission.csv')
test = test[['image_name']]
test = test.rename(columns={'image_name':'image_id'})
score1 = pd.read_csv('../../score/public_test_920.csv')[['image_name','target']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/public_test_925.csv')[['image_name','target']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/public_test_945.csv')[['image_name','target']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/public_test_946.csv')[['image_name','target']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/public_test_947.csv')[['image_name','target']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/public_test_949.csv')[['image_name','target']]
score6.columns = ['image_id','score6']
score7 = pd.read_csv('../../score/public_test_936.csv')[['image_name','target']]
score7.columns = ['image_id','score7']
test = test.merge(score1, on='image_id')
test = test.merge(score2, on='image_id')
test = test.merge(score3, on='image_id')
test = test.merge(score4, on='image_id')
test = test.merge(score5, on='image_id')
test = test.merge(score6, on='image_id')
test = test.merge(score7, on='image_id')

In [7]:
train.head().round(3)

,image_id,fold,target,score1,score2,score3,score4,score5,score6,score7
0,ISIC_2637011,0,0,0.006,0.221,0.019,0.022,0.097,0.066,0.023
1,ISIC_0015719,2,0,0.006,0.062,0.020,0.017,0.023,0.004,0.027
2,ISIC_0052212,4,0,0.006,0.093,0.030,0.023,0.028,0.024,0.038
3,ISIC_0068279,0,0,0.006,0.153,0.023,0.022,0.024,0.297,0.031
4,ISIC_0074268,4,0,0.006,0.051,0.024,0.019,0.021,0.025,0.020

In [8]:
test.head().round(3)

       image_id  score1  score2  score3  score4  score5  score6  score7
0  ISIC_0052060   0.006   0.120   0.027   0.021   0.029   0.036   0.032
1  ISIC_0052349   0.006   0.081   0.026   0.027   0.022   0.030   0.022
2  ISIC_0058510   0.006   0.040   0.026   0.023   0.024   0.020   0.026
3  ISIC_0073313   0.006   0.053   0.025   0.023   0.026   0.021   0.021
4  ISIC_0073502   0.009   0.182   0.033   0.023   0.040   0.161   0.027

In [9]:
train.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
fold    32691.0  2.02  1.42  0.00  1.00  2.00  3.00  4.00
target  32691.0  0.02  0.13  0.00  0.00  0.00  0.00  1.00
score1  32691.0  0.02  0.06  0.00  0.01  0.01  0.01  0.93
score2  32691.0  0.15  0.14  0.00  0.07  0.10  0.19  0.90
score3  32691.0  0.04  0.06  0.01  0.02  0.03  0.04  1.00
score4  32691.0  0.04  0.06  0.01  0.02  0.03  0.04  0.97
score5  32691.0  0.04  0.07  0.01  0.02  0.03  0.04  0.99
score6  32691.0  0.13  0.14  0.00  0.03  0.07  0.17  1.00
score7  32691.0  0.04  0.06  0.01  0.02  0.03  0.04  0.99

In [10]:
test.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
score1  10982.0  0.02  0.07  0.01  0.01  0.01  0.01  0.93
score2  10982.0  0.16  0.13  0.00  0.07  0.11  0.21  0.81
score3  10982.0  0.05  0.06  0.02  0.03  0.03  0.04  0.94
score4  10982.0  0.04  0.07  0.01  0.02  0.03  0.04  0.93
score5  10982.0  0.05  0.07  0.02  0.03  0.03  0.04  0.96
score6  10982.0  0.14  0.14  0.01  0.04  0.09  0.19  0.98
score7  10982.0  0.04  0.06  0.01  0.02  0.03  0.04  0.94

In [11]:
train[[x for x in FEATURES if '3' not in x]].corr().round(4)

        score1  score2  score4  score5  score6  score7
score1  1.0000  0.4659  0.8050  0.7472  0.4985  0.8280
score2  0.4659  1.0000  0.5321  0.5716  0.7048  0.5222
score4  0.8050  0.5321  1.0000  0.7200  0.5902  0.8436
score5  0.7472  0.5716  0.7200  1.0000  0.5430  0.7395
score6  0.4985  0.7048  0.5902  0.5430  1.0000  0.5610
score7  0.8280  0.5222  0.8436  0.7395  0.5610  1.0000

In [12]:
test[[x for x in FEATURES if '3' not in x]].corr().round(4)

        score1  score2  score4  score5  score6  score7
score1  1.0000  0.5775  0.9135  0.8917  0.5927  0.9375
score2  0.5775  1.0000  0.6127  0.6981  0.8732  0.6318
score4  0.9135  0.6127  1.0000  0.8461  0.6721  0.9395
score5  0.8917  0.6981  0.8461  1.0000  0.6670  0.8787
score6  0.5927  0.8732  0.6721  0.6670  1.0000  0.6702
score7  0.9375  0.6318  0.9395  0.8787  0.6702  1.0000

In [13]:
def fitModel(fold):
    scale = QuantileTransformer(n_quantiles=100, output_distribution='normal')
    train_subset = train[train['fold'] != fold].reset_index(drop=True).copy()
    valid_subset = train[train['fold'] == fold].reset_index(drop=True).copy()
    print('Data:', train_subset.shape, valid_subset.shape)
    valid_driver = valid_subset[['image_id','target']].copy()
    test_driver = test[['image_id']].copy()
    X_train, y_train = train_subset[FEATURES], train_subset[TARGET]
    X_valid, y_valid = valid_subset[FEATURES], valid_subset[TARGET]
    X_test = test[FEATURES]
    X_train = scale.fit_transform(X_train)
    X_valid = scale.transform(X_valid)
    X_test = scale.transform(X_test)
    model = LogisticRegression(C=1., fit_intercept=True)
    model = BaggingClassifier(model, n_estimators=10, max_samples=0.75)
    model.fit(X_train, y_train)
    valid_driver['score'] = model.predict_proba(X_valid)[:,1]
    test_driver['score'] = model.predict_proba(X_test)[:,1]
    print('Stacked AUC:', round(roc_auc_score(valid_driver.target, valid_driver.score), 4))
    print('Output:', test_driver.shape)
    return valid_driver, test_driver

In [14]:
valid_0, test_0 = fitModel(0)

Data: (26213, 10) (6478, 10)
Stacked AUC: 0.9489
Output: (10982, 2)

In [15]:
valid_1, test_1 = fitModel(1)

Data: (26217, 10) (6474, 10)
Stacked AUC: 0.9283
Output: (10982, 2)

In [16]:
valid_2, test_2 = fitModel(2)

Data: (26263, 10) (6428, 10)
Stacked AUC: 0.9401
Output: (10982, 2)

In [17]:
valid_3, test_3 = fitModel(3)

Data: (26013, 10) (6678, 10)
Stacked AUC: 0.9403
Output: (10982, 2)

In [18]:
valid_4, test_4 = fitModel(4)

Data: (26058, 10) (6633, 10)
Stacked AUC: 0.9561
Output: (10982, 2)

In [19]:
valid_data = valid_0.append(valid_1).append(valid_2).append(valid_3).append(valid_4)

In [20]:
test_data = test_0.append(test_1).append(test_2).append(test_3).append(test_4)

In [21]:
valid_data = valid_data.groupby(['image_id','target']).mean().reset_index()
test_data = test_data.groupby('image_id').mean().reset_index()

In [22]:
valid_data.shape, test_data.shape

((32691, 3), (10982, 2))

In [23]:
roc_auc_score(valid_data.target, valid_data.score)

0.9427017497404309

In [24]:
valid_data = valid_data[['image_id','score']]
valid_data.to_csv('../../score/regress_0_train.csv', index=False)

In [25]:
test_data.columns = ['image_name','target']
test_data.to_csv('../../score/regress_0_test.csv', index=False)

In [26]:
# 0.9492