In [1]:
from warnings import filterwarnings
filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import QuantileTransformer
from sklearn.linear_model import LogisticRegression
np.random.seed(2017)

In [3]:
FEATURES = ['score' + str(x+1) for x in range(9)]
FEATURES.remove('score1')
TARGET = ['target']

In [4]:
train = pd.read_csv('../../data/combined/data.csv')
train = train[train['source'] == 'ISIC20']
train = train[['image_id','fold','target']]
score1 = pd.read_csv('../../score/metadata_train_score.csv')[['image_name','score']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/version0_train_score.csv')[['image_name','score']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/version1_train_score.csv')[['image_name','score']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/version2_train_score.csv')[['image_name','score']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/version3_train_score.csv')[['image_name','score']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/version4_train_score.csv')[['image_name','score']]
score6.columns = ['image_id','score6']
score7 = pd.read_csv('../../score/version5_train_score.csv')[['image_name','score']]
score7.columns = ['image_id','score7']
score8 = pd.read_csv('../../score/version6_train_score.csv')[['image_name','score']]
score8.columns = ['image_id','score8']
score9 = pd.read_csv('../../score/version11_train_score.csv')[['image_name','score']]
score9.columns = ['image_id','score9']
train = train.merge(score1, on='image_id')
train = train.merge(score2, on='image_id')
train = train.merge(score3, on='image_id')
train = train.merge(score4, on='image_id')
train = train.merge(score5, on='image_id')
train = train.merge(score6, on='image_id')
train = train.merge(score7, on='image_id')
train = train.merge(score8, on='image_id')
train = train.merge(score9, on='image_id')

In [5]:
for idx in range(9):
    idx += 1
    try:
        print('Model:',idx,'AUC:',roc_auc_score(train.target, train['score'+str(idx)]))
    except:
        pass

Model: 1 AUC: 0.7892955637114458
Model: 2 AUC: 0.9203608668781098
Model: 3 AUC: 0.9215456656898539
Model: 4 AUC: 0.9321140056957823
Model: 5 AUC: 0.9309696498321444
Model: 6 AUC: 0.927716418014452
Model: 7 AUC: 0.9337159377376928
Model: 8 AUC: 0.9157784316069277
Model: 9 AUC: 0.9333300814594411

In [6]:
test = pd.read_csv('../../data/combined/sample_submission.csv')
test = test[['image_name']]
test = test.rename(columns={'image_name':'image_id'})
score1 = pd.read_csv('../../score/metadata_test_score.csv')[['image_name','target']]
score1.columns = ['image_id','score1']
score2 = pd.read_csv('../../score/version0_test_score.csv')[['image_name','target']]
score2.columns = ['image_id','score2']
score3 = pd.read_csv('../../score/version1_test_score.csv')[['image_name','target']]
score3.columns = ['image_id','score3']
score4 = pd.read_csv('../../score/version2_test_score.csv')[['image_name','target']]
score4.columns = ['image_id','score4']
score5 = pd.read_csv('../../score/version3_test_score.csv')[['image_name','target']]
score5.columns = ['image_id','score5']
score6 = pd.read_csv('../../score/version4_test_score.csv')[['image_name','target']]
score6.columns = ['image_id','score6']
score7 = pd.read_csv('../../score/version5_test_score.csv')[['image_name','target']]
score7.columns = ['image_id','score7']
score8 = pd.read_csv('../../score/version5_test_score.csv')[['image_name','target']]
score8.columns = ['image_id','score8']
score9 = pd.read_csv('../../score/version11_test_score.csv')[['image_name','target']]
score9.columns = ['image_id','score9']
test = test.merge(score1, on='image_id')
test = test.merge(score2, on='image_id')
test = test.merge(score3, on='image_id')
test = test.merge(score4, on='image_id')
test = test.merge(score5, on='image_id')
test = test.merge(score6, on='image_id')
test = test.merge(score7, on='image_id')
test = test.merge(score8, on='image_id')
test = test.merge(score9, on='image_id')

In [7]:
train.head().round(3)

,image_id,fold,target,score1,score2,score3,score4,score5,score6,score7,score8,score9
0,ISIC_2637011,0,0,0.014,0.219,0.161,0.053,0.000,0.000,0.020,0.016,0.000
1,ISIC_0015719,2,0,0.016,0.167,0.206,0.002,0.000,0.000,0.000,0.003,0.000
2,ISIC_0052212,4,0,0.015,0.212,0.192,0.019,0.000,0.001,0.003,0.002,0.001
3,ISIC_0068279,0,0,0.018,0.289,0.206,0.168,0.078,0.043,0.005,0.133,0.017
4,ISIC_0074268,4,0,0.016,0.215,0.160,0.002,0.000,0.000,0.001,0.001,0.000

In [8]:
test.head().round(3)

,image_id,score1,score2,score3,score4,score5,score6,score7,score8,score9
0,ISIC_0052060,0.018,0.175,0.179,0.006,0.000,0.002,0.002,0.002,0.000
1,ISIC_0052349,0.018,0.151,0.163,0.009,0.000,0.001,0.000,0.000,0.000
2,ISIC_0058510,0.016,0.190,0.176,0.004,0.000,0.001,0.014,0.014,0.000
3,ISIC_0073313,0.018,0.178,0.171,0.009,0.000,0.002,0.000,0.000,0.000
4,ISIC_0073502,0.018,0.236,0.251,0.090,0.002,0.004,0.074,0.074,0.001

In [9]:
train.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
fold    32691.0  2.02  1.42  0.00  1.00  2.00  3.00  4.00
target  32691.0  0.02  0.13  0.00  0.00  0.00  0.00  1.00
score1  32691.0  0.02  0.01  0.01  0.01  0.02  0.02  0.10
score2  32691.0  0.23  0.10  0.07  0.17  0.20  0.26  0.87
score3  32691.0  0.24  0.11  0.06  0.17  0.21  0.27  0.87
score4  32691.0  0.16  0.24  0.00  0.01  0.04  0.19  1.00
score5  32691.0  0.05  0.15  0.00  0.00  0.00  0.02  1.00
score6  32691.0  0.05  0.14  0.00  0.00  0.00  0.02  1.00
score7  32691.0  0.05  0.14  0.00  0.00  0.00  0.02  1.00
score8  32691.0  0.06  0.14  0.00  0.00  0.01  0.04  1.00
score9  32691.0  0.05  0.16  0.00  0.00  0.00  0.01  1.00

In [10]:
test.describe().round(2).T

          count  mean   std   min   25%   50%   75%   max
score1  10982.0  0.02  0.00  0.01  0.02  0.02  0.02  0.08
score2  10982.0  0.25  0.10  0.11  0.18  0.21  0.28  0.83
score3  10982.0  0.26  0.10  0.12  0.19  0.22  0.29  0.81
score4  10982.0  0.19  0.24  0.00  0.02  0.06  0.27  1.00
score5  10982.0  0.07  0.16  0.00  0.00  0.01  0.05  1.00
score6  10982.0  0.06  0.14  0.00  0.00  0.01  0.04  0.98
score7  10982.0  0.07  0.15  0.00  0.00  0.01  0.07  1.00
score8  10982.0  0.07  0.15  0.00  0.00  0.01  0.07  1.00
score9  10982.0  0.07  0.16  0.00  0.00  0.00  0.04  1.00

In [11]:
train[[x for x in FEATURES if '3' not in x]].corr().round(4)

        score2  score4  score5  score6  score7  score8  score9
score2  1.0000  0.8188  0.6774  0.6653  0.6751  0.6631  0.6652
score4  0.8188  1.0000  0.6769  0.6740  0.6933  0.6512  0.6761
score5  0.6774  0.6769  1.0000  0.7278  0.6709  0.6471  0.7035
score6  0.6653  0.6740  0.7278  1.0000  0.6923  0.6335  0.7119
score7  0.6751  0.6933  0.6709  0.6923  1.0000  0.7235  0.7445
score8  0.6631  0.6512  0.6471  0.6335  0.7235  1.0000  0.6352
score9  0.6652  0.6761  0.7035  0.7119  0.7445  0.6352  1.0000

In [12]:
test[[x for x in FEATURES if '3' not in x]].corr().round(4)

        score2  score4  score5  score6  score7  score8  score9
score2  1.0000  0.9121  0.7929  0.7892  0.7639  0.7639  0.8075
score4  0.9121  1.0000  0.7661  0.7786  0.7527  0.7527  0.7861
score5  0.7929  0.7661  1.0000  0.8033  0.7464  0.7464  0.8228
score6  0.7892  0.7786  0.8033  1.0000  0.7413  0.7413  0.8591
score7  0.7639  0.7527  0.7464  0.7413  1.0000  1.0000  0.8286
score8  0.7639  0.7527  0.7464  0.7413  1.0000  1.0000  0.8286
score9  0.8075  0.7861  0.8228  0.8591  0.8286  0.8286  1.0000

In [13]:
def fitModel(fold):
    scale = QuantileTransformer(n_quantiles=100, output_distribution='normal')
    train_subset = train[train['fold'] != fold].reset_index(drop=True).copy()
    valid_subset = train[train['fold'] == fold].reset_index(drop=True).copy()
    print('Data:', train_subset.shape, valid_subset.shape)
    valid_driver = valid_subset[['image_id','target']].copy()
    test_driver = test[['image_id']].copy()
    X_train, y_train = train_subset[FEATURES], train_subset[TARGET]
    X_valid, y_valid = valid_subset[FEATURES], valid_subset[TARGET]
    X_test = test[FEATURES]
    X_train = scale.fit_transform(X_train)
    X_valid = scale.transform(X_valid)
    X_test = scale.transform(X_test)
    model = LogisticRegression(C=1., fit_intercept=True)
    model.fit(X_train, y_train)
    print('Weights:', model.coef_.round(4))
    valid_driver['score'] = model.predict_proba(X_valid)[:,1]
    test_driver['score'] = model.predict_proba(X_test)[:,1]
    print('Stacked AUC:', round(roc_auc_score(valid_driver.target, valid_driver.score), 4))
    print('Output:', test_driver.shape)
    return valid_driver, test_driver

In [14]:
valid_0, test_0 = fitModel(0)

Data: (26213, 12) (6478, 12)
Weights: [[0.1166 0.3424 0.3508 0.5227 0.5079 0.4743 0.1093 0.3744]]
Stacked AUC: 0.9587
Output: (10982, 2)

In [15]:
valid_1, test_1 = fitModel(1)

Data: (26217, 12) (6474, 12)
Weights: [[0.1732 0.3747 0.1842 0.662  0.3795 0.6459 0.1619 0.2676]]
Stacked AUC: 0.9399
Output: (10982, 2)

In [16]:
valid_2, test_2 = fitModel(2)

Data: (26263, 12) (6428, 12)
Weights: [[0.0837 0.4264 0.25   0.6091 0.4801 0.4377 0.2434 0.317 ]]
Stacked AUC: 0.9392
Output: (10982, 2)

In [17]:
valid_3, test_3 = fitModel(3)

Data: (26013, 12) (6678, 12)
Weights: [[0.1791 0.4767 0.1192 0.5438 0.514  0.5162 0.1735 0.2848]]
Stacked AUC: 0.9517
Output: (10982, 2)

In [18]:
valid_4, test_4 = fitModel(4)

Data: (26058, 12) (6633, 12)
Weights: [[0.0532 0.3211 0.1932 0.7142 0.4201 0.4794 0.2809 0.3189]]
Stacked AUC: 0.9576
Output: (10982, 2)

In [19]:
valid_data = valid_0.append(valid_1).append(valid_2).append(valid_3).append(valid_4)

In [20]:
test_data = test_0.append(test_1).append(test_2).append(test_3).append(test_4)

In [21]:
valid_data = valid_data.groupby(['image_id','target']).mean().reset_index()
test_data = test_data.groupby('image_id').mean().reset_index()

In [22]:
valid_data.shape, test_data.shape

((32691, 3), (10982, 2))

In [23]:
roc_auc_score(valid_data.target, valid_data.score)

0.9495862705169569

In [24]:
valid_data = valid_data[['image_id','score']]
valid_data.to_csv('../../score/regress_1_train.csv', index=False)

In [25]:
test_data.columns = ['image_name','target']
test_data.to_csv('../../score/regress_1_test.csv', index=False)

In [26]:
# 0.9503